export const moviesMock = [
	{
		adult: false,
		backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
		genre_ids: [28, 878, 12],
		id: 27205,
		original_language: 'en',
		original_title: 'Inception',
		overview:
			'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
		popularity: 101.906,
		poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
		release_date: '2010-07-15',
		title: 'Inception',
		video: false,
		vote_average: 8.4,
		vote_count: 36668,
	},
	{
		adult: false,
		backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
		genre_ids: [12, 18, 878],
		id: 157336,
		original_language: 'en',
		original_title: 'Interstellar',
		overview:
			'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
		popularity: 180.053,
		poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
		release_date: '2014-11-05',
		title: 'Interstellar',
		video: false,
		vote_average: 8.445,
		vote_count: 35814,
	},
	{
		adult: false,
		backdrop_path: '/iYY8wiLHASWDxhGWTXfqr4XOAGG.jpg',
		genre_ids: [16, 10751, 28, 12, 878],
		id: 14613,
		original_language: 'en',
		original_title: 'Next Avengers: Heroes of Tomorrow',
		overview:
			"The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
		popularity: 13.998,
		poster_path: '/fpG1NDbcLV2a7c8X7LC4FPISBT7.jpg',
		release_date: '2008-09-02',
		title: 'Next Avengers: Heroes of Tomorrow',
		video: false,
		vote_average: 6.915,
		vote_count: 270,
	},
];
